### ISSUE TITLE
Ansiblle V12 support

### ISSUE THREAD

**Issue by crpb** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense#137]
Hey,
as i currently run debian testing on my new workstation (and the stable release is just around the corner) and the maintainer packaged ansible v12 last month i can't use the roles anymore as the conditionals fail.

Ref: [Ansible V12 Porting Guide](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_12.html#broken-conditionals)

This probably affects all roles 🙈

**Comment by zerwes** [comment]
Hello @crpb 
We mostly use the latest stable ansible release (sometimes with a delay of a few days after the release) in a fixed combination of `ansible/ansible-core` packages.
Currently this is:
```
ansible==11.5.0
ansible-core==2.18.5
```

`ansible 12.0.0a4` is in alpha and `ansible-core 2.19.0b4` in beta according to the versioning.
trixie as no fixed release date announced yet and is IMHO even not yet in the full freeze state.

Major ansible releases have always been some fun in the past (but I have to admit it is getting better with the time).
So thank you for pointing out that we have a some of work to do, as it will surely not be the only role having trouble.

I will start investigating this and keep you updated here.
For the meantime  I recommend you to use a venv installation of the current stable ansible releases.

**Comment by crpb** [comment]
> trixie as no fixed release date announced yet and is IMHO even not yet in the full freeze state.

yeah, but my **new** workstation from lenovo did freeze up with zfs on root when starting a libvirt vm so i had to switch :--).



> For the meantime I recommend you to use a venv installation of the current stable ansible releases.

ahh right, didn't even think of that 🙈 . will try my luck with pipx and the versions you mentioned.

**Comment by zerwes** [comment]
... yes, sometimes there are external constraints forcing you to use testing - I usually switch to it after passing the freeze state ... if I find the time :-(

if it helps, here our current dev env setup requirements file:
```
ansible==11.5.0
ansible-core==2.18.5
yamllint==1.35.1
ansible-lint==25.4.0
ansible-compat==25.1.5
pre-commit==3.7.0
ansible-pylibssh==1.1.0
molecule==24.2.1
molecule-plugins==23.5.3
docker==7.0.0
dnspython==2.6.1
netaddr==1.2.1
lxml==5.2.1
xmltodict==0.13.0
jmespath==1.0.1
Jinja2==3.1.4
PyYAML==6.0.2
HiYaPyCo==0.5.5
paramiko==3.4.0
requests==2.31.0
passlib==1.7.4
bcrypt==4.0.1  # https://github.com/Homebrew/homebrew-core/issues/160525
## The following requirements were added by pip freeze:
attrs==25.1.0
black==25.1.0
bracex==2.5.post1
certifi==2025.1.31
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.4.1
click==8.1.8
click-help-colors==0.9.4
cryptography==44.0.0
distlib==0.3.9
enrich==1.2.7
filelock==3.17.0
identify==2.6.6
idna==3.10
importlib_metadata==8.6.1
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mypy-extensions==1.0.0
nodeenv==1.9.1
packaging==24.2
pathspec==0.12.1
platformdirs==4.3.6
pluggy==1.5.0
pycparser==2.22
Pygments==2.19.1
PyNaCl==1.5.0
referencing==0.36.2
resolvelib==1.0.1
rich==13.9.4
rpds-py==0.22.3
ruamel.yaml==0.18.10
ruamel.yaml.clib==0.2.12
subprocess-tee==0.4.2
typing_extensions==4.12.2
urllib3==2.3.0
virtualenv==20.29.1
wcmatch==10.0
zipp==3.21.0
```

and from the Makefile the snippet to install:
`$(VENV_NAME)/bin/pip --disable-pip-version-check install -r requirements.txt`

Since a long time we moved away from the deb packages, as they are mostly outdated (or as in the current case one step in the future 🙃 ), and we even moved away from src installs to a venv an pip.

Using a venv with a defined and clean setup (we provide some Makefile targets for the dev's and some task in ansible to ensure a sane state) brings us the best result.

If you need more hints, just let me know ...

**Comment by zerwes** [comment]
https://github.com/ansible/ansible/issues/85100
https://github.com/ansible/ansible/issues/85053
this breaks our neck at the moment ...

**Comment by zerwes** [comment]
using
```
ansible==12.0.0a4
ansible-core==2.19.0b4
```
test file
```yaml
- hosts: localhost
  gather_facts: false
  become: false
  vars:
    _checkelementscount:
      results:
        - _checkelements: address
          count: 0
        - _checkelements: network
          count: 0
        - _checkelements: any
          count: 1
  tasks:
    - ansible.builtin.set_fact:
        _foundcheckelements1: "[ {% for e in _checkelementscount.results %}{% if e['count'] | int == 1 %}'{{ e['_checkelements'] }}',{% endif %}{% endfor %} ]"
    - ansible.builtin.debug:
        var: _foundcheckelements1

    - ansible.builtin.set_fact:
        _foundcheckelements2: [ "{% for e in _checkelementscount.results %}{% if e['count'] | int == 1 %}'{{ e['_checkelements'] }}',{% endif %}{% endfor %}" ]
    - ansible.builtin.debug:
        var: _foundcheckelements2

    - ansible.builtin.set_fact:
        _foundcheckelements3: "{{ (_foundcheckelements3 | default([])) + [item._checkelements] }}"
      when: item.count | int > 0
      with_items: "{{ _checkelementscount.results }}"
    - ansible.builtin.debug:
        var: _foundcheckelements3
```
result
```yaml
    "_foundcheckelements1": "[ 'any', ]"


    "_foundcheckelements2": [
        "'any',"
    ]


    "_foundcheckelements3": [
        "any"
    ]
```
no:3 is the right result but this would mean to rewrite all inline templates!
in this case the solution is quite simple, but for more komplex structures this will not be the case ...

I think we must put this on hold until the bug is fixed in ansible 12
