### ISSUE TITLE
group management with multiple members not working

### ISSUE THREAD

**Issue by mueller-tobias** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense#30]
i'm currently a bit struggeling with the group tasks. I didn't find a suitable variable construct that add more then one member to the group.

Here's an example
```yaml
    opn_group:
      - name: test
        member:
        settings:
          - key: description
            value: Testgruppe
          - key: gid
            value: 2000
          - key: member
            value: 0
          - key: member
            value: 2000
          - key: member
            value: 2001
```

The [groups - add users to groups task](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/blob/f7bd4053b31a3432f5fd143bee336540ec9072ca/tasks/group.yml#L25) will never run, because [groups - count member nodes](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/blob/f7bd4053b31a3432f5fd143bee336540ec9072ca/tasks/group.yml#L14C9-L14C36) will count all member nodes from all groups.

But even when i remove the member count condition it's not working, because it is looking for item.1.member. But item.1 has only key and value. When i reformat my variable to something like this:
```yaml
      - name: admins
        settings:
          - member: 0
          - member: 2000
          - member: 2001
```
and remove the member count condition it will add the members. But it will add the members every time the playbook runs.

I would rework the tasks to something that works. I think a combination of the json_query filter and set_children instead of add children should do the job.

Are you using the group management? If so, how are your variables?

**Comment by zerwes** [comment]
Hello Tobias.
For now I am on holiday (you know,father, husband, etc :-)), as soon as I will be back on the working track I'll have a look at it. But AFAIR we do not use this task, at least not to extensive. It is a unmodified task from the original naturalis repo.

**Comment by zerwes** [comment]
Hello Tobias.
Sorry for the delay.
You are right. The task is not working as expected.
At least the member setting ist broken.
I tried a fix on the branch issue-30.
Can you please test if this fits your needs?
the var for thesting I used:
```yaml
opn_group:
  - name: g2
    settings:
      - key: gid
        value: 2001
      - key: description
        value: group two
      - key: member
        value: 2000
      - key: member
        value: 2001
```
